config/routes.rb
TelekopilkaPromo::Application.routes.draw do
  root "main#index"
  post "main/save"


  namespace :client do
    get "log_in" => "sessions#new", :as => "log_in"
    get "log_out" => "sessions#destroy", :as => "log_out"

    get "sign_up" => "users#new", :as => "sign_up"

    resource :profile
    resources :transactions
    resources :users
    resources :sessions
    root "home#index"
  end

  namespace :partner do
    get "log_in" => "sessions#new", :as => "log_in"
    get "log_out" => "sessions#destroy", :as => "log_out"

    get "sign_up" => "users#new", :as => "sign_up"

    get "history/index"

    get "payment/index" , :as => "payment"
    post "payment/create"

    resource :profile
    resources :transactions
    resources :users
    resources :sessions
    root "home#index"
  end

  namespace :investor do
  end

  get "/update_invoice", :controller => "partner/payment", :action => "update_invoice"
  get "/pay_declined", :controller => "partner/payment", :action => "pay_declined"
  get "/pay_successful", :controller => "partner/payment", :action => "pay_successful"

end

app/models/count_course.rb
# class CountCourse < ParseResource::Base
#   fields :coefficient
# end

app/models/history.rb
# class History < ParseResource::Base
#   fields :count, :sum, :is_ingoing, :is_confirmed, :invId, :history_type
#   #has_one :history_type, :class_name => 'HistoryType'
#
# end

app/models/history_type.rb
# class HistoryType < ParseResource::Base
#   #belongs_to :history, :class_name => 'History'
#
#   fields :name
#
# end

app/models/request_email.rb
class RequestEmail < ActiveRecord::Base
end

app/models/user.rb
# class User < ParseUser
#   # no validations included, but feel free to add your own
#   validates_presence_of :username
#
#   # you can add fields, like any other kind of Object...
#   fields :name, :bio
#
#   # but note that email is a special field in the Parse API.
#   fields :email, :balance
#
#   alias :email :username
# end

app/controllers/application_controller.rb
# coding: utf-8
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :set_locale

  def set_locale
    I18n.locale = extract_locale_from_tld || I18n.default_locale
  end

  def extract_locale_from_tld
    parsed_locale = request.host.split('.').last
    if parsed_locale == 'рф'
      parsed_locale = 'ru'
    end
    I18n.available_locales.include?(parsed_locale.to_sym) ? parsed_locale  : nil
  end

end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end

  def save
    @email = RequestEmail.new()
    @email.email = params[:request_email][:email]
    if @email.save && params[:request_email][:email].present?
      SystemMailer.send_registration_notice(@email).deliver
      redirect_to root_url
    else
      redirect_to root_url
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/client/base_client_helper.rb
module Client::BaseClientHelper
end

app/helpers/client/home_helper.rb
module Client::HomeHelper
end

app/helpers/client/profile_helper.rb
module Client::ProfileHelper
end

app/helpers/client/sessions_helper.rb
module Client::SessionsHelper
end

app/helpers/client/users_helper.rb
module Client::UsersHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/partner/history_helper.rb
module Partner::HistoryHelper
end

app/helpers/partner/home_helper.rb
module Partner::HomeHelper
end

app/helpers/partner/payment_helper.rb
module Partner::PaymentHelper
end

app/helpers/partner/profile_helper.rb
module Partner::ProfileHelper
end

app/helpers/partner/sessions_helper.rb
module Partner::SessionsHelper
end

app/helpers/partner/users_helper.rb
module Partner::UsersHelper
end

app/views/main/pages/sliders/_slide_1_1.html.erb
<div class="row head-bar">
  <div class="col-lg-3 col-sm-1 col-md-2 logo"><%= image_tag "logo-red.png" %></div>
  <div class="col-lg-7 col-sm-3 col-md-5 header"><h1><%= t(:slide1_head) %></h1></div>
  <div class="col-lg-2 col-sm-1 .col-md-1 menu">
    <div class="row"><%= link_to image_tag("menu-white.png"), "#menu" %> </div>
    <div class="row" style="height: 20px">&nbsp;</div>
    <div class="row"><%= link_to t(:client_profile), client_root_url %></div>
  </div>
</div>

<div class="row slide-content">
  <div class="col-lg-6 col-sm-3 col-md-5 col-lg-offset-3 col-md-offset-2 col-sm-offset-1 ">
    <h1><%= h t(:slide1_header).html_safe %></h1>

    <p style="font-weight: bold;"><%= t(:slide1_text) %></p>
    <ul>
      <li><%= t("slide_text.li1") %></li>
      <li><%= t("slide_text.li2") %></li>
      <li><%= t("slide_text.li3") %></li>
      <li><%= t("slide_text.li4") %></li>
      <li><%= t("slide_text.li5") %></li>
      <li><%= t("slide_text.li6") %></li>
    </ul>
    <p><%= t(:soon) %> <%= image_tag("appstore.png") %> <%= image_tag("gplay.png") %></p>
  </div>
  <div id="separate-iphone" class="col-lg-3 col-sm-1 col-md-2 ">
    <%= image_tag "iphone.png" %>
  </div>
</div>

app/views/main/pages/sliders/_slide_1_2.html.erb
<div class="row head-bar">
  <div class="col-lg-3 col-sm-1 col-md-2 logo"><%= image_tag "logo-red2.png" %></div>
  <div class="col-lg-7 col-sm-3 col-md-5 header"><h1><%= t("slide_1_2.head") %></h1></div>
  <div class="col-lg-2 col-sm-1 .col-md-1 menu">
    <div class="row"><%= link_to image_tag("menu-red.png"), "#menu" %> </div>
    <div class="row" style="height: 20px">&nbsp;</div>
    <div class="row"><%= link_to t("slide_1_2.partner_profile"), partner_root_url %></div>
  </div>
</div>

<div class="row slide-content">

  <div id="iphone-container" class="col-lg-4 col-sm-2 col-md-1 col-lg-offset-1 col-md-offset-1 col-sm-offset-1 ">
    <%= image_tag "iphone-1.png", :class => "phone-1" %>
    <%= image_tag "iphone-2.png", :class => "phone-2"  %>
    <%= image_tag "iphone-3.png", :class => "phone-3"  %>
  </div>

  <div class="col-lg-6 col-sm-3 col-md-5">
    <h1><%= h t("slide_1_2.header").html_safe %></h1>

    <p style="font-weight: bold;"><%= t("slide_1_2.text").html_safe %></p>
    <ul>
      <li><%= t("slide_1_2.li1") %></li>
      <li><%= t("slide_1_2.li2") %></li>
      <li><%= t("slide_1_2.li3") %></li>
      <li><%= t("slide_1_2.li4") %></li>
      <li><%= t("slide_1_2.li5") %></li>
      <li><%= t("slide_1_2.li6") %></li>
    </ul>
  </div>

</div>

app/views/main/pages/sliders/_slide_1_3.html.erb
3

app/views/main/pages/sliders/_slide_1_4.html.erb
4